einride/can-go

- pkg/canrunner/run.go
- pkg/canrunner/run_test.go
Check before starting the transmit loop if cyclic transmission has already been requested and enable it if so.
> canrunner: Set cyclic transmission on RunMessageTransmitter init

- internal/identifiers/case.go
- internal/identifiers/case_test.go
- pkg/dbc/analysis/passes/valuedescriptions/analyzer.go
- pkg/dbc/analysis/passes/valuedescriptions/analyzer_test.go
2 small changes
* Allow the description field of a value descriptor to start with numbers (but still required the first letter after the numbers to be upper case)
* Change the lint marker for when linting value descriptors to point to the description rather than the value
> value description lint

- README.md
Improve the README by adding some examples on how to work with the socketcan and dbc parsing API
> chore: add some API documentation to the README

- pkg/dbc/parser.go
- testdata/dbc/example/example.dbc
- testdata/dbc/example/example.dbc.golden
In the case of attribute defines of type `INT` the parser crashes on integers expressed in scientific notation. E.g `BA_DEF_ SG_  "SPN" INT -3.4E+038 3.4E+038;` which looks like a float but is to be interpreted as an integer.
* Try and parse as float and then convert to int64. Ensure large numbers can be represented.
> fix(parser): add support for scientific notation integers

- internal/generate/compile_test.go
- internal/generate/file.go
- testdata/dbc/example/example.dbc
- testdata/dbc/example/example.dbc.golden
- testdata/gen/go/example/example.dbc.go
This replaces non-alphanumeric characters in descriptions with _ when generating the Go enums.
Fixes #30
> fix: generate - handle enum descriptions with spaces

- .github/workflows/ci.yml
- internal/generate/compile.go
- pkg/canjson/encode.go
- pkg/cantext/encode_test.go
- pkg/descriptor/signal.go
- pkg/descriptor/valuedescription.go
- testdata/gen/go/example/example.dbc.go
Currently, 32 bit can signals with value table definied values that are greater than int32 max are not supported.
This change should allow for all 32 bit unsigned values to be supported as well as all 64 bit signed integer signal values.
> feat(descriptor): use int64 to represent value descriptor values

- .github/workflows/ci.yml
Otherwise goreleaser does not publish artifacts to the correct release.
> fix(ci): fetch git tags before running goreleaser

- internal/generate/file.go
This fixes issue where code generation on dbc files with name containing
dashes, underscores, and dots fails due to incorrectly generated package name.
> fix(generate): clean up go package name

- pkg/candevice/device_others.go
Fixes the following for non-linux host when running make:
```
[go-lint]
pkg/candevice/device_others.go:10:22: undeclared name: `Device` (typecheck)
func New(_ string) (*Device, error) {
^
[go-lint] exit status 1
[go-review] exit status 1
```
---
Awesome that other OSs are taken into consideration and the not supported error is returned. With this change, the error will now get propagated to the non-linux user when using the `candevice` package because the `Device` type will exist.
> fix(candevice): add empty device struct for non-linux

- pkg/candevice/device_others.go
Primarily to improve the local development experience a little bit for non-linux users, i.e., a minimal working LSP autocomplete and a compilable program. WDYT?
> chore(candevice): add exported methods to enable LSP for non-linux users

- .github/CODEOWNERS
aet-platform and aet-data has merged into this team.
> chore(codeowners): transfer ownership to team-ads-platform

- pkg/canrunner/run_test.go
Go 1.21 added an optimization that broke one of our tests. Comparing context is not well-defined in Go so we compare a value inside the context instead.
This should work regardless of Go version I hope...
> test: go 1.21 compatibility

- pkg/candevice/device_linux.go
The GitHub rebase wasn't all knowing and didn't account for a previous change.
> fix(candevice): undefined type

- pkg/candevice/device_linux.go
It'll be easier to mock candevice functionality in other packages.
> feat: add interface

- README.md
We received an issue (#264) about having the wrong module path in go.mod. This commit aims to resolve the issue by making it clearer.
Fixes #264.
> chore(README): update examples to show import path

- internal/generate/compile.go
- internal/generate/compile_test.go
- internal/generate/example_test.go
- internal/generate/file.go
- pkg/descriptor/signal.go
- testdata/dbc-invalid/example/example_float32_invalid_signal_length.dbc
- testdata/dbc-invalid/example/example_float32_invalid_signal_name.dbc
- testdata/dbc-invalid/example/example_float64_signal.dbc
- testdata/dbc/example/example.dbc
- testdata/dbc/example/example.dbc.golden
- testdata/gen/go/example/example.dbc.go
Hi everyone!
This PR introduces support of floating point signals to golang code generation from DBC files. Floating point signals differs in the next aspects:
* Values are stored using bit representation of the floating point.
* Because of the previous point conversion needs to be a reinterpret cast on top if the bit representation. For example, for 32-bit float it will be `(*float32)(unsafe.Pointer(&i))`
* Float nature of the value is represented in DBC file using `SIG_VALTYPE_ <message_id> <signal_name> : <type_val>;`. `type_val` can be `0` for integer values, `1` for float32 and `2` for float64. Parsing of this is implemented in library already.
This PR doesn't touch next topics for now:
* Testing of the generated files. If tests are needed I'll be grateful if you point me on how …
> [+] Support for floating point signals.

- .gitignore
- internal/generate/compile_test.go
- internal/generate/file.go
- testdata/gen/go/example/example.dbc.go
Previously we used the setters and getters in the CopyFrom method. The
getters and setters both caps a signal to be within [min, max] range.
This meant that if we used CopyFrom from a message which contained an
out-of-bounds signal the new value would not keep the same signal
value.
This commit updates the CopyFrom implementation to instead unmarshal
the generated CAN frame from the original message.
**BREAKING CHANGE**: This changes CopyFrom to accept a message instead of
a message reader to copy from, however mostly test code should be
affected.
> fix(cantool): CopyFrom preserves signal values that are out-of-range

- internal/generate/file.go
- testdata/gen/go/example/example.dbc.go
For physical signals that have value table definitions we generate getters and setters that operate on the raw signal value, to give users access to check if signal values correspond to a named constant, or to write named constants to the signal.
However, there are use-cases (especially for sending test data) for writing raw values to any physical signal and therefore this commit adds generation of raw getters and setters to all physical signals.
> feat(cantool): generate raw setters and getters for physical signals

- internal/generate/example_test.go
- internal/generate/file.go
- testdata/gen/go/example/example.dbc.go
When updating the signature for CopyFrom we accidentally broke a workflow where receive messages in a `canrunner.Node` and then copy the data from them using `CopyFrom`. This commit restores CopyFrom to accept a "message reader" type, but extends that type to also require that values implement `Frame() can.Frame`.
All messages generated by cantool already implements `Frame() can.Frame` so only mocks should be affected.
BREAKING CHANGE: This restores old signature of CopyFrom to accept a message reader instead of a message instance to copy from.
> fix(cantool)!: CopyFrom accepts canrunner.Node Rx messages

- .github/workflows/release.yml
- .github/workflows/review.yml
- .sage/main.go
- Makefile
To prevent breakage from the goreview repo being decommissioned.
All linting now done by GolangCI-Lint.
> ci: remove deprecated goreview

- .sage/go.mod
- go.mod
One of our dependencies requires Go 1.20, which means that the project is not compilable with Go 1.19. This commit updates the module files to demand the correct version.
This is not a breaking change since the repository was not buildable with Go 1.19 and thus we should not be breaking anything for anybody.
> fix: bump Golang version to go1.20
